### Generated by rprotoc. DO NOT EDIT!
### <proto file: protobuf\demo.proto>
# 
# package google.protobuf;
# enum EDemoCommands {
# 	DEM_Error = -1;
# 	DEM_Stop = 0;
# 	DEM_FileHeader = 1;
# 	DEM_FileInfo = 2;
# 	DEM_SyncTick = 3;
# 	DEM_SendTables = 4;
# 	DEM_ClassInfo = 5;
# 	DEM_StringTables = 6;
# 	DEM_Packet = 7;
# 	DEM_SignonPacket = 8;
# 	DEM_ConsoleCmd = 9;
# 	DEM_CustomData = 10;
# 	DEM_CustomDataCallbacks = 11;
# 	DEM_UserCmd = 12;
# 	DEM_FullPacket = 13;
# 	DEM_Max = 14;
# 	DEM_IsCompressed = 112;
# }
# 
# message CDemoFileHeader {
# 	required string demo_file_stamp = 1;
# 	optional int32 network_protocol = 2;
# 	optional string server_name = 3;
# 	optional string client_name = 4;
# 	optional string map_name = 5;
# 	optional string game_directory = 6;
# 	optional int32 fullpackets_version = 7;
# 	optional bool allow_clientside_entities = 8;
# 	optional bool allow_clientside_particles = 9;
# }
# 
# message CGameInfo {
# 	message CDotaGameInfo {
# 		message CPlayerInfo {
# 			optional string hero_name = 1;
# 			optional string player_name = 2;
# 			optional bool is_fake_client = 3;
# 			optional uint64 steamid = 4;
# 			optional int32 game_team = 5;
# 		}
# 
# 		message CHeroSelectEvent {
# 			optional bool is_pick = 1;
# 			optional uint32 team = 2;
# 			optional uint32 hero_id = 3;
# 		}
# 
# 		optional uint32 match_id = 1;
# 		optional int32 game_mode = 2;
# 		optional int32 game_winner = 3;
# 		repeated CGameInfo.CDotaGameInfo.CPlayerInfo player_info = 4;
# 		optional uint32 leagueid = 5;
# 		repeated CGameInfo.CDotaGameInfo.CHeroSelectEvent picks_bans = 6;
# 		optional uint32 radiant_team_id = 7;
# 		optional uint32 dire_team_id = 8;
# 		optional string radiant_team_tag = 9;
# 		optional string dire_team_tag = 10;
# 		optional uint32 end_time = 11;
# 	}
# 
# 	optional CGameInfo.CDotaGameInfo dota = 4;
# }
# 
# message CDemoFileInfo {
# 	optional float playback_time = 1;
# 	optional int32 playback_ticks = 2;
# 	optional int32 playback_frames = 3;
# 	optional CGameInfo game_info = 4;
# }
# 
# message CDemoPacket {
# 	optional int32 sequence_in = 1;
# 	optional int32 sequence_out_ack = 2;
# 	optional bytes data = 3;
# }
# 
# message CDemoFullPacket {
# 	optional CDemoStringTables string_table = 1;
# 	optional CDemoPacket packet = 2;
# }
# 
# message CDemoSyncTick {
# }
# 
# message CDemoConsoleCmd {
# 	optional string cmdstring = 1;
# }
# 
# message CDemoSendTables {
# 	optional bytes data = 1;
# }
# 
# message CDemoClassInfo {
# 	message class_t {
# 		optional int32 class_id = 1;
# 		optional string network_name = 2;
# 		optional string table_name = 3;
# 	}
# 
# 	repeated CDemoClassInfo.class_t classes = 1;
# }
# 
# message CDemoCustomData {
# 	optional int32 callback_index = 1;
# 	optional bytes data = 2;
# }
# 
# message CDemoCustomDataCallbacks {
# 	repeated string save_id = 1;
# }
# 
# message CDemoStringTables {
# 	message items_t {
# 		optional string str = 1;
# 		optional bytes data = 2;
# 	}
# 
# 	message table_t {
# 		optional string table_name = 1;
# 		repeated CDemoStringTables.items_t items = 2;
# 		repeated CDemoStringTables.items_t items_clientside = 3;
# 		optional int32 table_flags = 4;
# 	}
# 
# 	repeated CDemoStringTables.table_t tables = 1;
# }
# 
# message CDemoStop {
# }
# 
# message CDemoUserCmd {
# 	optional int32 cmd_number = 1;
# 	optional bytes data = 2;
# }
# 

require_relative 'protobuf/message/message'
require_relative 'protobuf/message/enum'
require_relative 'protobuf/message/service'
require_relative 'protobuf/message/extend'

module D2Parser
  module Proto
    class EDemoCommands < ::Protobuf::Enum
      attr_accessor :DEM_IsCompressed
      defined_in __FILE__
      DEM_Error = value(:DEM_Error, -1)
      DEM_Stop = value(:DEM_Stop, 0)
      DEM_FileHeader = value(:DEM_FileHeader, 1)
      DEM_FileInfo = value(:DEM_FileInfo, 2)
      DEM_SyncTick = value(:DEM_SyncTick, 3)
      DEM_SendTables = value(:DEM_SendTables, 4)
      DEM_ClassInfo = value(:DEM_ClassInfo, 5)
      DEM_StringTables = value(:DEM_StringTables, 6)
      DEM_Packet = value(:DEM_Packet, 7)
      DEM_SignonPacket = value(:DEM_SignonPacket, 8)
      DEM_ConsoleCmd = value(:DEM_ConsoleCmd, 9)
      DEM_CustomData = value(:DEM_CustomData, 10)
      DEM_CustomDataCallbacks = value(:DEM_CustomDataCallbacks, 11)
      DEM_UserCmd = value(:DEM_UserCmd, 12)
      DEM_FullPacket = value(:DEM_FullPacket, 13)
      DEM_Max = value(:DEM_Max, 14)
      @DEM_IsCompressed = value(:DEM_IsCompressed, 112)
    end
    class CDemoFileHeader < ::Protobuf::Message
      defined_in __FILE__
      required :string, :demo_file_stamp, 1
      optional :int32, :network_protocol, 2
      optional :string, :server_name, 3
      optional :string, :client_name, 4
      optional :string, :map_name, 5
      optional :string, :game_directory, 6
      optional :int32, :fullpackets_version, 7
      optional :bool, :allow_clientside_entities, 8
      optional :bool, :allow_clientside_particles, 9
    end
    class CGameInfo < ::Protobuf::Message
      defined_in __FILE__
      class CDotaGameInfo < ::Protobuf::Message
        defined_in __FILE__
        class CPlayerInfo < ::Protobuf::Message
          defined_in __FILE__
          optional :string, :hero_name, 1
          optional :string, :player_name, 2
          optional :bool, :is_fake_client, 3
          optional :uint64, :steamid, 4
          optional :int32, :game_team, 5
        end
        class CHeroSelectEvent < ::Protobuf::Message
          defined_in __FILE__
          optional :bool, :is_pick, 1
          optional :uint32, :team, 2
          optional :uint32, :hero_id, 3
        end
        optional :uint32, :match_id, 1
        optional :int32, :game_mode, 2
        optional :int32, :game_winner, 3
        repeated :'CGameInfo::CDotaGameInfo::CPlayerInfo', :player_info, 4
        optional :uint32, :leagueid, 5
        repeated :'CGameInfo::CDotaGameInfo::CHeroSelectEvent', :picks_bans, 6
        optional :uint32, :radiant_team_id, 7
        optional :uint32, :dire_team_id, 8
        optional :string, :radiant_team_tag, 9
        optional :string, :dire_team_tag, 10
        optional :uint32, :end_time, 11
      end
      optional :'CGameInfo::CDotaGameInfo', :dota, 4
    end
    class CDemoFileInfo < ::Protobuf::Message
      defined_in __FILE__
      optional :float, :playback_time, 1
      optional :int32, :playback_ticks, 2
      optional :int32, :playback_frames, 3
      optional :CGameInfo, :game_info, 4
    end
    class CDemoPacket < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :sequence_in, 1
      optional :int32, :sequence_out_ack, 2
      optional :bytes, :data, 3
    end
    class CDemoFullPacket < ::Protobuf::Message
      defined_in __FILE__
      optional :CDemoStringTables, :string_table, 1
      optional :CDemoPacket, :packet, 2
    end
    class CDemoSyncTick < ::Protobuf::Message
      defined_in __FILE__
    end
    class CDemoConsoleCmd < ::Protobuf::Message
      defined_in __FILE__
      optional :string, :cmdstring, 1
    end
    class CDemoSendTables < ::Protobuf::Message
      defined_in __FILE__
      optional :bytes, :data, 1
    end
    class CDemoClassInfo < ::Protobuf::Message
      defined_in __FILE__
      class Class_t < ::Protobuf::Message
        defined_in __FILE__
        optional :int32, :class_id, 1
        optional :string, :network_name, 2
        optional :string, :table_name, 3
      end
      repeated :'CDemoClassInfo::class_t', :classes, 1
    end
    class CDemoCustomData < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :callback_index, 1
      optional :bytes, :data, 2
    end
    class CDemoCustomDataCallbacks < ::Protobuf::Message
      defined_in __FILE__
      repeated :string, :save_id, 1
    end
    class CDemoStringTables < ::Protobuf::Message
      defined_in __FILE__
      class Items_t < ::Protobuf::Message
        defined_in __FILE__
        optional :string, :str, 1
        optional :bytes, :data, 2
      end
      class Table_t < ::Protobuf::Message
        defined_in __FILE__
        optional :string, :table_name, 1
        repeated :'CDemoStringTables::items_t', :items, 2
        repeated :'CDemoStringTables::items_t', :items_clientside, 3
        optional :int32, :table_flags, 4
      end
      repeated :'CDemoStringTables::table_t', :tables, 1
    end
    class CDemoStop < ::Protobuf::Message
      defined_in __FILE__
    end
    class CDemoUserCmd < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :cmd_number, 1
      optional :bytes, :data, 2
    end
  end
end