### Generated by rprotoc. DO NOT EDIT!
### <proto file: protobuf\usermessages.proto>
# 
# import "networkbasetypes.proto";
# package google.protobuf;
# enum EBaseUserMessages {
# 	UM_AchievementEvent = 1;
# 	UM_CloseCaption = 2;
# 	UM_CloseCaptionDirect = 3;
# 	UM_CurrentTimescale = 4;
# 	UM_DesiredTimescale = 5;
# 	UM_Fade = 6;
# 	UM_GameTitle = 7;
# 	UM_Geiger = 8;
# 	UM_HintText = 9;
# 	UM_HudMsg = 10;
# 	UM_HudText = 11;
# 	UM_KeyHintText = 12;
# 	UM_MessageText = 13;
# 	UM_RequestState = 14;
# 	UM_ResetHUD = 15;
# 	UM_Rumble = 16;
# 	UM_SayText = 17;
# 	UM_SayText2 = 18;
# 	UM_SayTextChannel = 19;
# 	UM_Shake = 20;
# 	UM_ShakeDir = 21;
# 	UM_StatsCrawlMsg = 22;
# 	UM_StatsSkipState = 23;
# 	UM_TextMsg = 24;
# 	UM_Tilt = 25;
# 	UM_Train = 26;
# 	UM_VGUIMenu = 27;
# 	UM_VoiceMask = 28;
# 	UM_VoiceSubtitle = 29;
# 	UM_SendAudio = 30;
# 	UM_MAX_BASE = 63;
# }
# 
# message CUserMsg_AchievementEvent {
# 	optional uint32 achievement = 1;
# }
# 
# message CUserMsg_CloseCaption {
# 	optional fixed32 hash = 1;
# 	optional float duration = 2;
# 	optional bool from_player = 3;
# }
# 
# message CUserMsg_CurrentTimescale {
# 	optional float current = 1;
# }
# 
# message CUserMsg_DesiredTimescale {
# 	optional float desired = 1;
# 	optional float duration = 2;
# 	optional uint32 interpolator = 3;
# 	optional float start_blend_time = 4;
# }
# 
# message CUserMsg_Fade {
# 	optional uint32 duration = 1;
# 	optional uint32 hold_time = 2;
# 	optional uint32 flags = 3;
# 	optional fixed32 color = 4;
# }
# 
# message CUserMsg_Shake {
# 	optional uint32 command = 1;
# 	optional float amplitude = 2;
# 	optional float frequency = 3;
# 	optional float duration = 4;
# }
# 
# message CUserMsg_ShakeDir {
# 	optional CUserMsg_Shake shake = 1;
# 	optional CMsgVector direction = 2;
# }
# 
# message CUserMsg_Tilt {
# 	optional uint32 command = 1;
# 	optional bool ease_in_out = 2;
# 	optional CMsgVector angle = 3;
# 	optional float duration = 4;
# 	optional float time = 5;
# }
# 
# message CUserMsg_SayText {
# 	optional uint32 client = 1;
# 	optional string text = 2;
# 	optional bool chat = 3;
# }
# 
# message CUserMsg_SayText2 {
# 	optional uint32 client = 1;
# 	optional bool chat = 2;
# 	optional string format = 3;
# 	optional string prefix = 4;
# 	optional string text = 5;
# 	optional string location = 6;
# }
# 
# message CUserMsg_HudMsg {
# 	optional uint32 channel = 1;
# 	optional float x = 2;
# 	optional float y = 3;
# 	optional uint32 color1 = 4;
# 	optional uint32 color2 = 5;
# 	optional uint32 effect = 6;
# 	optional float fade_in_time = 7;
# 	optional float fade_out_time = 8;
# 	optional float hold_time = 9;
# 	optional float fx_time = 10;
# 	optional string message = 11;
# }
# 
# message CUserMsg_HudText {
# 	optional string message = 1;
# }
# 
# message CUserMsg_TextMsg {
# 	optional uint32 dest = 1;
# 	repeated string param = 2;
# }
# 
# message CUserMsg_GameTitle {
# }
# 
# message CUserMsg_ResetHUD {
# }
# 
# message CUserMsg_SendAudio {
# 	optional bool stop = 2;
# 	optional string name = 3;
# }
# 
# message CUserMsg_VoiceMask {
# 	repeated int32 audible_players_mask = 1;
# 	optional bool player_mod_enabled = 2;
# }
# 
# message CUserMsg_RequestState {
# }
# 
# message CUserMsg_HintText {
# 	optional string message = 1;
# }
# 
# message CUserMsg_KeyHintText {
# 	repeated string messages = 1;
# }
# 
# message CUserMsg_StatsCrawlMsg {
# }
# 
# message CUserMsg_StatsSkipState {
# 	optional int32 num_skips = 1;
# 	optional int32 num_players = 2;
# }
# 
# message CUserMsg_VoiceSubtitle {
# 	optional int32 ent_index = 1;
# 	optional int32 menu = 2;
# 	optional int32 item = 3;
# }
# 
# message CUserMsg_VGUIMenu {
# 	message Keys {
# 		optional string name = 1;
# 		optional string value = 2;
# 	}
# 
# 	optional string name = 1;
# 	optional bool show = 2;
# 	repeated CUserMsg_VGUIMenu.Keys keys = 3;
# }
# 
# message CUserMsg_Geiger {
# 	optional int32 range = 1;
# }
# 
# message CUserMsg_Rumble {
# 	optional int32 index = 1;
# 	optional int32 data = 2;
# 	optional int32 flags = 3;
# }
# 
# message CUserMsg_Train {
# 	optional int32 train = 1;
# }
# 
# message CUserMsg_SayTextChannel {
# 	optional int32 player = 1;
# 	optional int32 channel = 2;
# 	optional string text = 3;
# }
# 
# message CUserMsg_MessageText {
# 	optional uint32 color = 1;
# 	optional string text = 2;
# }
# 

require_relative 'protobuf/message/message'
require_relative 'protobuf/message/enum'
require_relative 'protobuf/message/service'
require_relative 'protobuf/message/extend'

require_relative 'networkbasetypes.pb'
module D2Parser
  module Proto
    class EBaseUserMessages < ::Protobuf::Enum
      defined_in __FILE__
      UM_AchievementEvent = value(:UM_AchievementEvent, 1)
      UM_CloseCaption = value(:UM_CloseCaption, 2)
      UM_CloseCaptionDirect = value(:UM_CloseCaptionDirect, 3)
      UM_CurrentTimescale = value(:UM_CurrentTimescale, 4)
      UM_DesiredTimescale = value(:UM_DesiredTimescale, 5)
      UM_Fade = value(:UM_Fade, 6)
      UM_GameTitle = value(:UM_GameTitle, 7)
      UM_Geiger = value(:UM_Geiger, 8)
      UM_HintText = value(:UM_HintText, 9)
      UM_HudMsg = value(:UM_HudMsg, 10)
      UM_HudText = value(:UM_HudText, 11)
      UM_KeyHintText = value(:UM_KeyHintText, 12)
      UM_MessageText = value(:UM_MessageText, 13)
      UM_RequestState = value(:UM_RequestState, 14)
      UM_ResetHUD = value(:UM_ResetHUD, 15)
      UM_Rumble = value(:UM_Rumble, 16)
      UM_SayText = value(:UM_SayText, 17)
      UM_SayText2 = value(:UM_SayText2, 18)
      UM_SayTextChannel = value(:UM_SayTextChannel, 19)
      UM_Shake = value(:UM_Shake, 20)
      UM_ShakeDir = value(:UM_ShakeDir, 21)
      UM_StatsCrawlMsg = value(:UM_StatsCrawlMsg, 22)
      UM_StatsSkipState = value(:UM_StatsSkipState, 23)
      UM_TextMsg = value(:UM_TextMsg, 24)
      UM_Tilt = value(:UM_Tilt, 25)
      UM_Train = value(:UM_Train, 26)
      UM_VGUIMenu = value(:UM_VGUIMenu, 27)
      UM_VoiceMask = value(:UM_VoiceMask, 28)
      UM_VoiceSubtitle = value(:UM_VoiceSubtitle, 29)
      UM_SendAudio = value(:UM_SendAudio, 30)
      UM_MAX_BASE = value(:UM_MAX_BASE, 63)
    end
    class CUserMsg_AchievementEvent < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :achievement, 1
    end
    class CUserMsg_CloseCaption < ::Protobuf::Message
      defined_in __FILE__
      optional :fixed32, :hash, 1
      optional :float, :duration, 2
      optional :bool, :from_player, 3
    end
    class CUserMsg_CurrentTimescale < ::Protobuf::Message
      defined_in __FILE__
      optional :float, :current, 1
    end
    class CUserMsg_DesiredTimescale < ::Protobuf::Message
      defined_in __FILE__
      optional :float, :desired, 1
      optional :float, :duration, 2
      optional :uint32, :interpolator, 3
      optional :float, :start_blend_time, 4
    end
    class CUserMsg_Fade < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :duration, 1
      optional :uint32, :hold_time, 2
      optional :uint32, :flags, 3
      optional :fixed32, :color, 4
    end
    class CUserMsg_Shake < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :command, 1
      optional :float, :amplitude, 2
      optional :float, :frequency, 3
      optional :float, :duration, 4
    end
    class CUserMsg_ShakeDir < ::Protobuf::Message
      defined_in __FILE__
      optional :CUserMsg_Shake, :shake, 1
      optional :CMsgVector, :direction, 2
    end
    class CUserMsg_Tilt < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :command, 1
      optional :bool, :ease_in_out, 2
      optional :CMsgVector, :angle, 3
      optional :float, :duration, 4
      optional :float, :time, 5
    end
    class CUserMsg_SayText < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :client, 1
      optional :string, :text, 2
      optional :bool, :chat, 3
    end
    class CUserMsg_SayText2 < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :client, 1
      optional :bool, :chat, 2
      optional :string, :format, 3
      optional :string, :prefix, 4
      optional :string, :text, 5
      optional :string, :location, 6
    end
    class CUserMsg_HudMsg < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :channel, 1
      optional :float, :x, 2
      optional :float, :y, 3
      optional :uint32, :color1, 4
      optional :uint32, :color2, 5
      optional :uint32, :effect, 6
      optional :float, :fade_in_time, 7
      optional :float, :fade_out_time, 8
      optional :float, :hold_time, 9
      optional :float, :fx_time, 10
      optional :string, :message, 11
    end
    class CUserMsg_HudText < ::Protobuf::Message
      defined_in __FILE__
      optional :string, :message, 1
    end
    class CUserMsg_TextMsg < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :dest, 1
      repeated :string, :param, 2
    end
    class CUserMsg_GameTitle < ::Protobuf::Message
      defined_in __FILE__
    end
    class CUserMsg_ResetHUD < ::Protobuf::Message
      defined_in __FILE__
    end
    class CUserMsg_SendAudio < ::Protobuf::Message
      defined_in __FILE__
      optional :bool, :stop, 2
      optional :string, :name, 3
    end
    class CUserMsg_VoiceMask < ::Protobuf::Message
      defined_in __FILE__
      repeated :int32, :audible_players_mask, 1
      optional :bool, :player_mod_enabled, 2
    end
    class CUserMsg_RequestState < ::Protobuf::Message
      defined_in __FILE__
    end
    class CUserMsg_HintText < ::Protobuf::Message
      defined_in __FILE__
      optional :string, :message, 1
    end
    class CUserMsg_KeyHintText < ::Protobuf::Message
      defined_in __FILE__
      repeated :string, :messages, 1
    end
    class CUserMsg_StatsCrawlMsg < ::Protobuf::Message
      defined_in __FILE__
    end
    class CUserMsg_StatsSkipState < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :num_skips, 1
      optional :int32, :num_players, 2
    end
    class CUserMsg_VoiceSubtitle < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :ent_index, 1
      optional :int32, :menu, 2
      optional :int32, :item, 3
    end
    class CUserMsg_VGUIMenu < ::Protobuf::Message
      defined_in __FILE__
      class Keys < ::Protobuf::Message
        defined_in __FILE__
        optional :string, :name, 1
        optional :string, :value, 2
      end
      optional :string, :name, 1
      optional :bool, :show, 2
      repeated :'CUserMsg_VGUIMenu::Keys', :keys, 3
    end
    class CUserMsg_Geiger < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :range, 1
    end
    class CUserMsg_Rumble < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :index, 1
      optional :int32, :data, 2
      optional :int32, :flags, 3
    end
    class CUserMsg_Train < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :train, 1
    end
    class CUserMsg_SayTextChannel < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :player, 1
      optional :int32, :channel, 2
      optional :string, :text, 3
    end
    class CUserMsg_MessageText < ::Protobuf::Message
      defined_in __FILE__
      optional :uint32, :color, 1
      optional :string, :text, 2
    end
  end
end